name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get update && apt-get install -y python-pip && pip install --upgrade pip

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

          echo "##Model metrics" > report.md 
          cat metrics.txt >> report.md
           
          echo "## data viz " >> report.md
          cml-publish feature_importance.png --md >> report.md
          
          echo "## Data viz" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          
          
          cml-send-report -p report.md 
